# Generated by Django 5.0.6 on 2026-07-02 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_label', models.CharField(max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='venues.section')),
            ],
            options={
                'db_table': 'rows',
                'ordering': ['sort_order'],
                'unique_together': {('section', 'row_label')},
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'venues',
                'indexes': [models.Index(fields=['city', 'state'], name='venues_city_76f08d_idx')],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='venues.venue'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP'), ('WHEELCHAIR', 'Wheelchair')], default='REGULAR', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.row')),
            ],
            options={
                'db_table': 'seats',
                'unique_together': {('row', 'seat_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('venue', 'name')},
        ),
    ]
