# Generated by Django 5.0.6 on 2026-07-02 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('requested_seats', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('OFFERED', 'Offered'), ('EXPIRED', 'Expired'), ('PROMOTED', 'Promoted')], default='WAITING', max_length=15)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('promoted_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_promotion', to='bookings.booking')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='events.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waitlist_entries',
                'indexes': [models.Index(fields=['show', 'status', 'position'], name='waitlist_en_show_id_8806ea_idx'), models.Index(fields=['offer_expires_at'], name='waitlist_en_offer_e_2cee6a_idx')],
                'unique_together': {('show', 'user')},
            },
        ),
    ]
