# Generated by Django 5.0.6 on 2026-07-02 08:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('MOVIE', 'Movie'), ('CONCERT', 'Concert'), ('PLAY', 'Play'), ('OTHER', 'Other')], max_length=20)),
                ('poster_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doors_open', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='events.event')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='venues.venue')),
            ],
            options={
                'db_table': 'shows',
            },
        ),
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_categories', to='events.show')),
            ],
            options={
                'db_table': 'price_categories',
            },
        ),
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HELD', 'Held'), ('BOOKED', 'Booked'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=15)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('held_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_seats', to=settings.AUTH_USER_MODEL)),
                ('price_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.pricecategory')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='venues.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='events.show')),
            ],
            options={
                'db_table': 'show_seats',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='events_event_t_c9f56c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='events_is_acti_45ba60_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organiser'], name='events_organis_fb2096_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['start_time'], name='shows_start_t_aada35_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['event', 'start_time'], name='shows_event_i_575b6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricecategory',
            unique_together={('show', 'name')},
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['show', 'status'], name='show_seats_show_id_5285d2_idx'),
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['held_by', 'hold_expires_at'], name='show_seats_held_by_b9f984_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='showseat',
            unique_together={('show', 'seat')},
        ),
    ]
